### ISSUE TITLE
hypervisor virto_net thread panics during increased network traffic

### ISSUE THREAD

**Issue by ericooper** [intel/cloud-hypervisor#166]
When transferring larger files between the cloud-hypervisor instance and the cloud-hypervisor host with ftp or using iperf the hypervisor virtio net driver panics. 

An example using iperf with RUST_BACKTRACE=full:

```
root@cloud-hypervisor:~# iperf -c 192.168.122.1
------------------------------------------------------------
Client connecting to 192.168.122.1, TCP port 5001
TCP window size: 45.0 KByte (default)`
------------------------------------------------------------
[  3] local 192.168.122.48 port 60928 connected with 192.168.122.1 port 5001
thread 'virtio_net' panicked at 'index 68168 out of range for slice of length 65562', src/libcore/slice/mod.rs:2560:5
stack backtrace:
   0:     0x563c486a00d3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h50ebfb8734a81144
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x563c4869b9db - std::sys_common::backtrace::_print::hc7fdae4fb6b58d2d
                               at src/libstd/sys_common/backtrace.rs:71
   2:     0x563c4869edb6 - std::panicking::default_hook::{{closure}}::hc55d0892611a29ff
                               at src/libstd/sys_common/backtrace.rs:59
                               at src/libstd/panicking.rs:197
   3:     0x563c4869eb49 - std::panicking::default_hook::h3c8a3df5d3469668
                               at src/libstd/panicking.rs:211
   4:     0x563c4869f4bf - std::panicking::rust_panic_with_hook::h24c9a1c35b1f49cc
                               at src/libstd/panicking.rs:474
   5:     0x563c4869f041 - std::panicking::continue_panic_fmt::h8ed9632bdd4b9299
                               at src/libstd/panicking.rs:381
   6:     0x563c4869ef25 - rust_begin_unwind
                               at src/libstd/panicking.rs:308
   7:     0x563c486b2d5c - core::panicking::panic_fmt::h0d6d5c8b201e3246
                               at src/libcore/panicking.rs:85
   8:     0x563c486b3095 - core::slice::slice_index_len_fail::hbeb3bb6238e26ddb
                               at src/libcore/slice/mod.rs:2560
   9:     0x563c4864fb63 - <core::ops::range::Range<usize> as core::slice::SliceIndex<[T]>>::index::h81996df1128f0a05
                               at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/slice/mod.rs:2737
  10:     0x563c4864f3df - <core::ops::range::RangeTo<usize> as core::slice::SliceIndex<[T]>>::index::h68171e90c696eebe
                               at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/slice/mod.rs:2783
  11:     0x563c48653ae7 - core::slice::<impl core::ops::index::Index<I> for [T]>::index::h35c8d0f1b55df247
                               at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/slice/mod.rs:2543
  12:     0x563c4856173d - vm_virtio::net::NetEpollHandler::process_tx::hc0e59df1eb662e73
                               at vm-virtio/src/net.rs:280
  13:     0x563c48563039 - vm_virtio::net::NetEpollHandler::run::hc620a357feddf352
                               at vm-virtio/src/net.rs:359
  14:     0x563c4857b935 - <vm_virtio::net::Net as vm_virtio::device::VirtioDevice>::activate::{{closure}}::hb1ae3cdd5d0f00f5
                               at vm-virtio/src/net.rs:575
  15:     0x563c48585850 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9f0163d90ac9dfa0
                               at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/sys_common/backtrace.rs:136
  16:     0x563c48552073 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h2f0e7d6ff3bbd45b
                               at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/thread/mod.rs:470
  17:     0x563c485831d3 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h2bbc7c384267a2be
                               at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panic.rs:309
  18:     0x563c48586465 - std::panicking::try::do_call::h3ec84c8df5391d8f
                               at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panicking.rs:293
  19:     0x563c486a2e19 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:87
  20:     0x563c4858614c - std::panicking::try::h51bddf9e523e42c5
                               at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panicking.rs:272
  21:     0x563c48583373 - std::panic::catch_unwind::h7e11966d3df4e115
                               at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panic.rs:388
  22:     0x563c48551deb - std::thread::Builder::spawn_unchecked::{{closure}}::hd8b82b6bd908931b
                               at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/thread/mod.rs:469
  23:     0x563c48544203 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h46b4b668912241c0
                               at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/ops/function.rs:231
  24:     0x563c48692ffe - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h4cac16ae2114a837
                               at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702
  25:     0x563c486a25af - std::sys::unix::thread::Thread::new::thread_start::h2adc1b80820f790e
                               at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702
                               at src/libstd/sys_common/thread.rs:14
                               at src/libstd/sys/unix/thread.rs:80
  26:     0x7f0a391bafa2 - start_thread
  27:     0x7f0a390d14ce - clone
  28:                0x0 - <unknown>
```

a similar test using scp transferring larger files the ssh based transfer gets aborted with a 
> message authentication code incorrect 

_pls note: whether this is related or represents a separate issue due to nic offloading settings remains to be seen._

monitoring the read_count variable indicates that perhaps read_count exceeds the length of the tx frame buffer in net.rs line 280 under load.

**Comment by rbradford** [comment]
With the fix in #169 I see 
```
cloud@cloud:~$ iperf -c 192.168.2.1
------------------------------------------------------------
Client connecting to 192.168.2.1, TCP port 5001
TCP window size: 85.0 KByte (default)
------------------------------------------------------------
[  3] local 192.168.2.2 port 51314 connected with 192.168.2.1 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  12.5 GBytes  10.7 Gbits/sec
cloud@cloud:~$ 

```

**Comment by sboeuf** [comment]
Yes me too!

@ericooper thanks for spotting this issue :)

**Comment by ericooper** [comment]
Excellent and thanks for following-up on this swiftly. Appreciate it.
